---
title: "PAA_Sansone_Sparks"
author: "Corey Sparks & Lloyd Potter"
date: "September 12, 2018"
output: html_document
---





```{r}

library(survey)
library(dplyr)
library(car)
library(ggplot2)

library(tigris)
options(tigris_class = "sf")
pumas<-pumas(state = "TX", year = 2014, cb = T)

#table(data$educd)
```
```{r, eval=FALSE}

load(url("https://github.com/coreysparks/tx_education/blob/master/ipums_subset.Rdata?raw=true"))
#set.seed(1115)
#samp <- sample(1:dim(sub)[1], replace = F, 100000)
```

Prepare variables:
```{r}

sub$pwt <- sub$perwt/100
sub$hwt <- sub$hhwt/100

sub$hisp <- Recode(sub$hispan, recodes = "9=NA; 1:4='Hispanic'; 0='NonHispanic'")
sub$race_rec <- Recode(sub$race, recodes = "1='White'; 2='Black'; 3='Other'; 4:6='Asian'; 7:9='Other'")
sub$race_eth <- interaction(sub$hisp, sub$race_rec, sep = "_")
sub$race_eth  <- as.factor(ifelse(substr(as.character(sub$race_eth),1,8) == "Hispanic", "Hispanic", as.character(sub$race_eth)))
sub$race_eth <- relevel(sub$race_eth, ref = "NonHispanic_White")

sub$male <- ifelse(sub$sex == 1,1,0)
sub$usborn <- Recode(sub$bpl, recodes = "1:120=1; 121:900=0; else=NA")

sub$educ_level<- Recode(sub$educd, recodes = "2:61='0LT_HS';62:64='1_HSD/GED';65:80='2_somecoll';90:100='2_somecoll'; 81:83='3_AssocDegree';101='4_bachelordegree'; 110:116='4_BAplus_GradDegree'; else=NA")

sub$employed <- Recode(sub$empstatd, recodes = "10:12=1; 20:22=0; else=NA")
sub$inhs<- Recode(sub$gradeatt, recodes = "5=1; else=0")
sub$incollege <- Recode(sub$gradeatt, recodes = "6:7=1; else=0")

sub<-sub%>%
  mutate(hsgrad_coll = as.factor(case_when(.$educ_level=='1_HSD/GED' & .$incollege==0 ~ '0hsgrad_notincollege',
                                 .$educ_level=='1_HSD/GED' & .$incollege==1 ~ '1hsgrad_incollege')))

#sub$edu_scal_inc <- ave(sub$incwage, sub$male, FUN = scale)
sub$inc_adj <- ifelse(sub$year == 2005, sub$incwage*1.23,
                      ifelse(sub$year == 2006, sub$incwage*1.18,
                             ifelse(sub$year == 2007, sub$incwage*1.16,
                                    ifelse(sub$year %in% c(2008,2009), sub$incwage*1.1, 
                                           ifelse(sub$year == 2010, sub$incwage*1.1,
                                                  ifelse(sub$year == 2011, sub$incwage*1.07,
                                                         ifelse(sub$year == 2012, sub$incwage*1.05,
                                                                ifelse(sub$year == 2013, sub$incwage*1.03, 
                                                                       ifelse(sub$year == 2014, sub$incwage*1.01,
                                                                              ifelse(sub$year == 2015, sub$incwage*1.01, sub$incwage))))))))))
```


```{r}
sub<-haven::zap_labels(sub)
sub2<-sub%>%
  filter(age%in%c(16:25), educ_level=="1_HSD/GED")
 #filter(educ_level=="1_HSD/GED")
#sub$nonmet<-ifelse(sub$met2013)
des<-svydesign(ids=~cluster, weights = ~pwt, data=sub2)
```

```{r}
puma_est<-svyby(formula = ~incollege, by = ~race_eth+metro, des, FUN=svymean, na.rm=T )

puma_est$metro_label<-Recode(puma_est$metro, recodes="1='Non Metro'; 2='Metro Central City'; 3='Metro Suburban'")
puma_est<-mutate(puma_est, race_eth2 = case_when(puma_est$race_eth =="NonHispanic_White" ~ 'Non Latinx White', 
                                                puma_est$race_eth =="Hispanic" ~ 'Latinx',
                                                puma_est$race_eth =="NonHispanic_Asian" ~ 'Non Latinx Asian',
                                                puma_est$race_eth =="NonHispanic_Black" ~ 'Non Latinx Black',
                                                puma_est$race_eth =="NonHispanic_Other" ~ 'Non Latinx Other'))

puma_est%>%
  filter(metro!=0, metro!=4)%>%
  ggplot()+
  geom_col(aes(x=metro_label, y=incollege, fill=race_eth2,group=race_eth2), position="dodge2", lwd=1)+
  scale_color_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00"))+
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00"))+
  ylab("Proportion Enrolled")+
  xlab("Metro Status")+labs(fill = "Race/Ethnicity")+
  ggtitle(label="Proportion of College Enrolled High School Graduates by Metro Status", subtitle = "Population aged 16 to 25")

ggsave(filename = "enrolled.png", width = 9, height = 8, units = "in", dpi = 150)


puma_est2<-svyby(formula = ~race_eth, by = ~metro, des, FUN=svymean, na.rm=T )
library(reshape2)
puma_est2<-melt(puma_est2[, 1:6], id="metro")
puma_est2$metro_label<-Recode(puma_est2$metro, recodes="1='Non Metro'; 2='Metro Central City'; 3='Metro Suburban'")
puma_est2<-puma_est2%>%filter(metro!=0, metro!=4)
puma_est2<-mutate(puma_est2, race_eth = case_when(puma_est2$variable =="race_ethNonHispanic_White" ~ 'Non Latinx White', 
                                                puma_est2$variable =="race_ethHispanic" ~ 'Latinx',
                                                puma_est2$variable =="race_ethNonHispanic_Asian" ~ 'Non Latinx Asian',
                                                puma_est2$variable =="race_ethNonHispanic_Black" ~ 'Non Latinx Black',
                                                puma_est2$variable =="race_ethNonHispanic_Other" ~ 'Non Latinx Other'))
puma_est2%>%
  filter(metro!=0, metro!=4)%>%
  ggplot()+geom_col(aes(x=metro_label, y=value , group=race_eth, fill=race_eth ),position="dodge2", lwd=2)+
  scale_color_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00"))+
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00"))+
  ylab("Proportion of Population")+
  xlab("Metro Status")+ labs(fill = "Race/Ethnicity")+
  ggtitle(label="Proportion of Race/Ethnic Groups by Metro Status", subtitle = "Proportion of Population aged 16 to 25")
ggsave(filename = "populationcomp.png", width = 9, height = 8, units = "in", dpi = 150)+ylim(c(0, .7))
```

## make a map of the distributions of race/ethnicyt by pumas

```{r}
puma_est<-svyby(formula = ~incollege, by = ~race_eth+factor(puma), des, FUN=svymean, na.rm=T )
puma_est$pumace10<-sprintf("%05d", as.numeric(as.character(puma_est$`factor(puma)`)))
brks<-classIntervals(var=100*puma_est$incollege, n=5, style="jenks")[2]$brks

library(sf)
sts<-core_based_statistical_areas(cb = T, year = 2015)
sts<-sts%>%
  #st_boundary()%>%
  filter(LSAD=="M1")
sts<-sts[grep(sts$NAME,pattern =  "TX"),]
sts_coords <- as.data.frame(sf::st_coordinates(sts))

tx<-states(cb=T)
tx<-tx%>%
  filter(STATEFP==48)%>%
  st_boundary()
#sts<-st_transform(sts, crs=102740)
library(classInt)
puma_dat<- geo_join(pumas, puma_est[puma_est$race_eth=="Hispanic",],by_sp="PUMACE10", by_df="pumace10")

puma_dat%>%
  #filter(race_eth=="Hispanic")%>%
  mutate(enroll_cut=cut(100*incollege,breaks = brks,include.lowest = T))%>%
  #st_transform(crs = 102740)%>%
  ggplot(aes(fill=enroll_cut, color=NA))+
  geom_sf()+
  scale_fill_brewer(palette = "Blues",na.value = "grey50") +
  scale_color_brewer(palette = "Blues",na.value = "grey50")+
   labs(fill = "% Enrolled")+
  ggtitle("Proportion of Latinx High School Graduates Enrolled in College", subtitle ="Ages 16 to 25")+
  geom_sf(data=sts,fill=NA, color="black")+
  geom_sf_label(data=sts, aes(label=gsub(",.*$", "", sts$NAME)), fill=NA, color="black", label.size = 0)+
  geom_sf(data=tx, fill=NA, color="black")

ggsave(filename = "Hisppumamap.png", width = 12, height = 10, units = "in", dpi = 250)



puma_dat<- geo_join(pumas, puma_est[puma_est$race_eth=="NonHispanic_White",],by_sp="PUMACE10", by_df="pumace10")

puma_dat%>%
  #filter(race_eth=="Hispanic")%>%
  mutate(enroll_cut=cut(100*incollege,breaks =brks,include.lowest = T))%>%
  #st_transform(crs = 102740)%>%
  ggplot(aes(fill=enroll_cut))+
  geom_sf()+
  scale_fill_brewer(palette = "Blues",na.value = "grey50") +
  scale_color_brewer(palette = "Blues",na.value = "grey50")+
   labs(fill = "% Enrolled")+
  ggtitle("Proportion of Non Latinx White High School Graduates Enrolled in College", subtitle ="Ages 16 to 25")+
  geom_sf(data=sts,fill=NA, color="black")+
  geom_sf_label(data=sts, aes(label=gsub(",.*$", "", sts$NAME)), fill=NA, color="black", label.size = 0)+
  geom_sf(data=tx, fill=NA, color="black")

ggsave(filename = "whitepumamap.png", width = 12, height = 10, units = "in", dpi = 250)

puma_dat<- geo_join(pumas, puma_est[puma_est$race_eth=="NonHispanic_Black",],by_sp="PUMACE10", by_df="pumace10")

library(sf)
puma_dat%>%
  #filter(race_eth=="Hispanic")%>%
  mutate(enroll_cut=cut(100*incollege,breaks = brks,include.lowest = T),
         cv=se/incollege)%>%
 # filter(cv<.4)%>%
  #st_transform(crs = 102740)%>%
  ggplot(aes(fill=enroll_cut))+
  geom_sf()+
  scale_fill_brewer(palette = "Blues",na.value = "grey50") +
  scale_color_brewer(palette = "Blues",na.value = "grey50")+
   labs(fill = "% Enrolled")+
  ggtitle("Proportion of Non Latinx Black High School Graduates Enrolled in College", subtitle ="Ages 16 to 25")+
  geom_sf(data=sts,fill=NA, color="black")+
  geom_sf_label(data=sts, aes(label=gsub(",.*$", "", sts$NAME)), fill=NA, color="black", label.size = 0)+
  geom_sf(data=tx, fill=NA, color="black")

ggsave(filename = "blackpumamap.png", width = 12, height = 10, units = "in", dpi = 250)

```




```{r}

anova(glm(incollege~factor(puma), sub, family=binomial), test="Chisq")
library(lme4)
#sub$pumafact<-factor(sub$puma)
sub$pumfact<-as.factor(sprintf("%05d", as.numeric(as.character(sub$puma))))
fit<-glmer(incollege~race_eth+factor(metro)+scale(age)+male+factor(year)+(1|pumfact),weights=pwt/mean(pwt, na.rm=T), family=binomial, data=sub, subset=metro%in%c(1,2,3), control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

summary(fit)

fit2<-glmer(incollege~race_eth*factor(metro)+scale(age)+male+factor(year)+(1|pumfact),weights=pwt/mean(pwt, na.rm=T), family=binomial, data=sub, subset=metro%in%c(1,2,3), control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

summary(fit2)

anova(fit, fit2, test="Chisq")

library(stargazer)
myexp<-function(x) exp(x)
stargazer(fit, type = "html", style="default", out="~/paalogregoutput.html", t.auto = F, p.auto = F, ci=T,
          column.labels = c("College Enrollment"),dep.var.labels.include=F,keep.stat = c("n", "aic", "lr"),mean.sd = T,summary.stat = c("mean", "sd"),apply.coef = myexp)


```
